/**
 * TurboSlop — exports.
 *
 * One place that turns a stored design into a downloadable artefact, shared by
 * the control surface and the tests. Everything travels: the page, the full
 * decision record, the bundled OFL fonts WITH their licences, every asset the
 * spec references (supplied or generated, with alt text, dimensions, source,
 * credit and licence intact), and a self-contained single file.
 *
 * The ZIP writer is dependency-free (`zip.ts`); entry names are UTF-8 flagged
 * so a supplied image with a non-ASCII name extracts correctly everywhere.
 */
import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { stripEmphasis } from './content.js';
import { getDesign } from './registry.js';
import { createZip, type ZipEntry } from './zip.js';
import type { DesignSpec } from './types.js';

const ASSET_RE = /^[a-z0-9][a-z0-9-]*\/[A-Za-z0-9._-]+\.(png|jpg|jpeg|webp)$/;

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.woff2': 'font/woff2',
  '.md': 'text/markdown; charset=utf-8',
};

/**
 * Inline every relative asset as a data URI, producing ONE portable file.
 *
 * This is the "copy it in one shot" export: paste into an email, a gist, a
 * CMS field, anything. Fonts AND their licence file are inlined too — OFL
 * requires the licence to travel with the font, and a single-file export that
 * dropped it would be shipping unlicensed-looking type.
 */
export async function inlineAssets(html: string, outDir: string): Promise<string> {
  const refs = [...html.matchAll(/(?:src|href|url\()["']?(assets\/[^"')]+|fonts\/[^"')]+)/g)].map(
    (m) => m[1] ?? m[2]!,
  );
  let out = html;
  let inlinedFont = false;
  for (const ref of new Set(refs)) {
    const isAsset = ref.startsWith('assets/');
    const rel = ref.replace(/^(assets|fonts)\//, '');
    if (isAsset && !ASSET_RE.test(rel)) continue;
    if (!isAsset && !/^[A-Za-z0-9._-]+\.(woff2|md)$/.test(rel)) continue;
    try {
      const buf = await readFile(path.join(outDir, isAsset ? 'assets' : 'fonts', rel));
      const mime = MIME[path.extname(rel).toLowerCase()] ?? 'application/octet-stream';
      out = out.split(ref).join(`data:${mime};base64,${buf.toString('base64')}`);
      if (!isAsset && rel.endsWith('.woff2')) inlinedFont = true;
    } catch {
      /* a missing file leaves the reference intact rather than breaking the page */
    }
  }

  /* The OFL requires the licence to travel WITH the font software. When the
     fonts are embedded as data URIs, this file IS the carrier, so the licence
     text is embedded too — as a comment, readable in any editor. */
  if (inlinedFont && !out.includes('TURBO SLOP — BUNDLED FONT LICENCES')) {
    try {
      const licences = await readFile(path.join(outDir, 'fonts', 'LICENSES.md'), 'utf8');
      out += `\n<!--\nTURBO SLOP — BUNDLED FONT LICENCES\nThe typefaces embedded above are distributed under the licences below.\n\n${licences}\n-->\n`;
    } catch {
      /* no licence file on disk: the reference in fonts/ stays the fallback */
    }
  }
  return out;
}

/** A short human brief describing how a design was produced, for the export. */
export function designReadme(spec: DesignSpec, slug: string): string {
  const dec = spec.decisions
    .map((d) => `| ${d.axis} | \`${d.picked}\` | ${d.confidence.toFixed(2)} | ${d.review ? '**review**' : ''} |`)
    .join('\n');
  const assets = spec.assets.length
    ? spec.assets
        .map((a) => {
          const base = `### ${a.slot || a.kind} — \`${path.basename(a.file)}\``;
          const meta =
            `- alt: ${a.alt}\n- dimensions: ${a.nativeWidth}×${a.nativeHeight}px\n- source: ${a.source}\n`;
          if (a.source === 'user') {
            return (
              `${base}\n\n${meta}` +
              `- credit: ${a.credit || '_not stated_'}\n- licence: ${a.license || '_not stated_'}\n`
            );
          }
          return (
            `${base}\n\n${meta}` +
            `- seed \`${a.seed}\`, steps ${a.steps}, guidance ${a.cfg}, ${(a.bytes / 1024).toFixed(0)} KB\n` +
            `- native resolution ${a.nativeWidth}x${a.nativeHeight} (generated)\n\n> ${a.prompt}\n`
          );
        })
        .join('\n')
    : '_No generated artwork — the layout uses its CSS gradient fallbacks._\n';

  const c = spec.content;
  return `# ${c?.brand ?? slug}${c ? ` — ${stripEmphasis(c.title)}` : ''}

${c?.description ?? ''}

Generated by **TurboSlop**. This file documents how, so the result can be
reproduced or audited.

## Brief

> ${spec.brief.split('\n').join('\n> ')}

## Decisions

Jev decided these; each carries a calibrated confidence.

| axis | choice | confidence | |
|---|---|---|---|
${dec}

Composite: **${spec.composite.normalized.toFixed(3)} / 1.000**
${spec.review.length ? `\nFlagged for review: ${spec.review.join(', ')}\n` : ''}
## Provenance

| | |
|---|---|
| blueprint | \`${spec.blueprint}\` |
| seed | \`${spec.seed}\` |
| decider | \`${spec.meta.decider}\` / \`${spec.meta.model}\` (${spec.meta.latencyMs} ms) |
| copy | \`${spec.meta.writer}\`${spec.meta.writer === 'llm' ? ` / \`${spec.meta.writerModel}\` (${spec.meta.writerLatencyMs} ms)` : ' (specimen content)'} |
| images | ${spec.meta.imageCount} at steps ${spec.meta.imageSteps} / guidance ${spec.meta.imageCfg} (${spec.meta.imageMs} ms) |
| decision cost | ~$${spec.meta.estimatedUsd.toFixed(6)} (Jev: input only) |
| writing cost | ~$${spec.meta.writerEstimatedUsd.toFixed(6)} (the writing half usually dominates) |
| **estimated total** | **~$${(spec.meta.estimatedUsd + spec.meta.writerEstimatedUsd).toFixed(6)}** |

## Files

- \`index.html\` — the page
- \`index.selfcontained.html\` — one file, fonts and artwork inlined
- \`design.spec.json\` — the full decision record, including every probability
- \`assets/\` — artwork with its metadata
- \`fonts/\` — the bundled OFL faces and \`LICENSES.md\`

## Generated artwork

${assets}
## Content

**${c ? stripEmphasis(c.tagline) : ''}**

${c?.lede ?? ''}

${(c?.aboutBody ?? []).join('\n\n')}
`;
}

/**
 * Build the ZIP for a stored design.
 *
 * Every asset the spec references is included (when present on disk), fonts
 * travel with their licences, and a self-contained page is added so the
 * archive works with no assets folder at all.
 */
export async function buildZip(outDir: string, slug: string): Promise<Buffer> {
  const loaded = await getDesign(outDir, slug);
  if (!loaded) throw new Error('design not found');
  const { spec } = loaded;

  const html = await readFile(path.join(outDir, `${slug}.html`), 'utf8');
  const entries: ZipEntry[] = [
    { path: 'index.html', data: html },
    { path: 'design.spec.json', data: await readFile(path.join(outDir, `${slug}.spec.json`)) },
    { path: 'README.md', data: designReadme(spec, slug) },
  ];

  for (const a of spec.assets) {
    const rel = a.file.replace(/^assets\//, '');
    if (!ASSET_RE.test(rel)) continue;
    try {
      entries.push({ path: a.file, data: await readFile(path.join(outDir, 'assets', rel)) });
    } catch {
      /* skip a missing asset rather than failing the whole export */
    }
  }

  try {
    for (const f of await readdir(path.join(outDir, 'fonts'))) {
      if (!f.endsWith('.woff2') && f !== 'LICENSES.md') continue;
      entries.push({ path: `fonts/${f}`, data: await readFile(path.join(outDir, 'fonts', f)) });
    }
  } catch {
    /* no bundled fonts on disk: the page still falls back to system faces */
  }

  try {
    entries.push({ path: 'index.selfcontained.html', data: await inlineAssets(html, outDir) });
  } catch {
    /* optional */
  }

  return createZip(entries);
}

/**
 * The RFC 6266 `Content-Disposition` value for a download.
 *
 * ASCII-safe fallback plus the UTF-8 form, so a slug that somehow carries a
 * non-ASCII character still produces a valid header (raw non-ASCII in an HTTP
 * header is the actual failure mode — Node throws `ERR_INVALID_CHAR`).
 */
export function contentDisposition(filename: string): string {
  const ascii = filename.replace(/[^\x20-\x7e]/g, '_').replace(/["\\]/g, '_');
  if (ascii === filename) return `attachment; filename="${filename}"`;
  const encoded = encodeURIComponent(filename).replace(/['()*]/g, (c) => `%${c.charCodeAt(0).toString(16)}`);
  return `attachment; filename="${ascii}"; filename*=UTF-8''${encoded}`;
}
