/**
 * TurboSlop — vendored Lucide icon geometry.
 *
 * GENERATED BY scripts/fetch-icons.ts — DO NOT EDIT BY HAND.
 * Re-run `npx tsx scripts/fetch-icons.ts` (`--refresh` to re-fetch) to verify or update.
 *
 * Upstream: https://github.com/lucide-icons/lucide at commit 3b9ea6d08707edc439f25a4c354cb0d6b8bee973 (release 1.47.0).
 * Raw pattern: https://raw.githubusercontent.com/lucide-icons/lucide/3b9ea6d08707edc439f25a4c354cb0d6b8bee973/icons/<name>.svg
 * Licence: ISC (SPDX: `ISC`). The verbatim upstream notice — the ISC licence
 * plus the MIT notice for the Feather-derived glyphs — lives in
 * `public/icons/LICENSES.md` and must travel with any redistribution of this data.
 *
 * Allowlist (69 glyphs, curated by module semantics): navigation (9), contact (9), commerce (8), content (10), data (8), process (8), trust (9), decoration (8).
 * Only geometry attributes are vendored; src/icons.ts wraps every glyph with the
 * house profile (24-grid, stroke 1.6, round caps/joins, currentColor, no fill),
 * exactly like the original family. This module is pure data: no fs, no network,
 * no clock, no randomness.
 */

/** Upstream commit the glyphs were fetched from (full SHA, immutable). */
export const LUCIDE_COMMIT = '3b9ea6d08707edc439f25a4c354cb0d6b8bee973';
/** Upstream release the pinned commit belongs to. */
export const LUCIDE_VERSION = '1.47.0';
/** Human-facing upstream repository. */
export const LUCIDE_SOURCE = 'https://github.com/lucide-icons/lucide';
/** Raw URL base: <base>/<name>.svg. */
export const LUCIDE_RAW_BASE = 'https://raw.githubusercontent.com/lucide-icons/lucide/3b9ea6d08707edc439f25a4c354cb0d6b8bee973/icons';
/** Upstream licence file for the pinned commit. */
export const LUCIDE_LICENSE_URL = 'https://raw.githubusercontent.com/lucide-icons/lucide/3b9ea6d08707edc439f25a4c354cb0d6b8bee973/LICENSE';
/** sha256 of (commit + curated allowlist): a re-run can tell whether the plan changed. */
export const LUCIDE_ALLOWLIST_SHA256 = 'ab67724c1a05a92cd27ed3789077403f3f71c10cdcc0d6a6a5a16b111d8969e3';
/** The one grid every glyph is drawn on. */
export const LUCIDE_GRID = 24;

/** Glyph names, in allowlist order. */
export const LUCIDE_ICON_NAMES = [
  'house',
  'menu',
  'arrow-right',
  'arrow-up-right',
  'chevron-right',
  'chevron-down',
  'external-link',
  'expand',
  'move-right',
  'mail',
  'at-sign',
  'send',
  'phone',
  'phone-call',
  'smartphone',
  'map-pin',
  'map-pinned',
  'navigation',
  'shopping-bag',
  'shopping-cart',
  'credit-card',
  'tag',
  'receipt-text',
  'package',
  'truck',
  'banknote',
  'file-text',
  'book-open',
  'pen-line',
  'quote',
  'image',
  'download',
  'newspaper',
  'message-square',
  'messages-square',
  'circle-question-mark',
  'chart-line',
  'chart-bar',
  'chart-pie',
  'database',
  'table',
  'calculator',
  'trending-up',
  'activity',
  'clock',
  'timer',
  'calendar',
  'calendar-days',
  'workflow',
  'list-checks',
  'git-branch',
  'refresh-cw',
  'shield',
  'shield-check',
  'lock',
  'key',
  'badge-check',
  'circle-check',
  'check',
  'award',
  'users',
  'sparkles',
  'star',
  'heart',
  'sun',
  'moon',
  'leaf',
  'zap',
  'flower',
] as const;
export type LucideIconName = (typeof LUCIDE_ICON_NAMES)[number];

/** The curated module semantics the allowlist is grouped by. */
export type LucideIconCategory = 'navigation' | 'contact' | 'commerce' | 'content' | 'data' | 'process' | 'trust' | 'decoration';

export interface LucideGlyph {
  category: LucideIconCategory;
  /** House roles this glyph can fulfil; see ICON_ROLE_GLYPHS in src/icons.ts. */
  roles: readonly string[];
  /** sha256 of the upstream SVG this geometry was normalised from. */
  sha256: string;
  /** Inner geometry. Presentation is stripped: the wrapper decides stroke/fill. */
  body: string;
}

export const LUCIDE_GLYPHS: { readonly [K in LucideIconName]: LucideGlyph } = {
  /* ---- navigation (9) ---- */
  'house': {
    category: 'navigation',
    roles: [],
    sha256: '28216c479005731ef5e382e7d8627eda2b129b019eb1f3d9de9f5915576d448e',
    body: '<path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"/><path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>',
  },
  'menu': {
    category: 'navigation',
    roles: [],
    sha256: 'af6491988ac1ba30dc5414f485bc48713e957e1edb0fbef4a0dd8691c3c21598',
    body: '<path d="M4 5h16"/><path d="M4 12h16"/><path d="M4 19h16"/>',
  },
  'arrow-right': {
    category: 'navigation',
    roles: ['nav-cta'],
    sha256: '288397fdb73bb4f783cf9eabb726ff47357df1d4e3f1201dd748090579f108b9',
    body: '<path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>',
  },
  'arrow-up-right': {
    category: 'navigation',
    roles: ['gallery-link'],
    sha256: '50b2503b9d11881142255466b7e3461d022b919735841c321d72003ac9959fe1',
    body: '<path d="M7 7h10v10"/><path d="M7 17 17 7"/>',
  },
  'chevron-right': {
    category: 'navigation',
    roles: ['nav-cta'],
    sha256: '2758143d7b2434e4aa7307dfd34405c87909ff4052f21b5f3f40d45224b4f19b',
    body: '<path d="m9 18 6-6-6-6"/>',
  },
  'chevron-down': {
    category: 'navigation',
    roles: [],
    sha256: '66ea878e72ed3488bb3b464c39dfdccee8d1f78e560dccea40e5e12da0e87e87',
    body: '<path d="m6 9 6 6 6-6"/>',
  },
  'external-link': {
    category: 'navigation',
    roles: ['gallery-link'],
    sha256: '3891241b8c3bfc3a8a930078f26ffc5a7e9763da6d0162ace2050b28d4c1d1fe',
    body: '<path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>',
  },
  'expand': {
    category: 'navigation',
    roles: ['gallery-link'],
    sha256: '3d57bfcb818a2ead60ccd221e5fdff0eaaaf39cdafc5bbec897a96eff1ddae36',
    body: '<path d="m15 15 6 6"/><path d="m15 9 6-6"/><path d="M21 16v5h-5"/><path d="M21 8V3h-5"/><path d="M3 16v5h5"/><path d="m3 21 6-6"/><path d="M3 8V3h5"/><path d="M9 9 3 3"/>',
  },
  'move-right': {
    category: 'navigation',
    roles: ['nav-cta'],
    sha256: '5d5cd515e240654303ee557b0010988c2b4fd319b99aec9d13b7c6c846a4e08f',
    body: '<path d="M18 8L22 12L18 16"/><path d="M2 12H22"/>',
  },
  /* ---- contact (9) ---- */
  'mail': {
    category: 'contact',
    roles: ['contact-email'],
    sha256: '3236a51d5b8ce9b0528cf2e6ad07e527bd636dded6f5a9d656072052b99caea8',
    body: '<path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"/><rect x="2" y="4" width="20" height="16" rx="2"/>',
  },
  'at-sign': {
    category: 'contact',
    roles: ['contact-email'],
    sha256: 'a71ec1918c3787172b16949262ca4c4a7c427c045367bb58f2c2cdbd87297c5e',
    body: '<circle cx="12" cy="12" r="4"/><path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8"/>',
  },
  'send': {
    category: 'contact',
    roles: ['contact-email'],
    sha256: 'a489257f447b808ab6b258ae888fa49686885bbc30a7a2774d97a01f11f9cd5e',
    body: '<path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"/><path d="m21.854 2.147-10.94 10.939"/>',
  },
  'phone': {
    category: 'contact',
    roles: ['contact-phone'],
    sha256: 'bd59dd10667cbe410a69e2fbbf4d9645d08abe862c8d89082bd4f533957859a8',
    body: '<path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384"/>',
  },
  'phone-call': {
    category: 'contact',
    roles: ['contact-phone'],
    sha256: 'fb043b89aa72cfc63e00f6f0dd91df779cbb80bbf88b32b6d58358d0d94257d1',
    body: '<path d="M13 2a9 9 0 0 1 9 9"/><path d="M13 6a5 5 0 0 1 5 5"/><path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384"/>',
  },
  'smartphone': {
    category: 'contact',
    roles: ['contact-phone'],
    sha256: 'f9fdb700b50feb5fc6436f53eb9813e9eb56a9071ac4cdcba69c7f7c1c13877d',
    body: '<rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><path d="M12 18h.01"/>',
  },
  'map-pin': {
    category: 'contact',
    roles: ['contact-address'],
    sha256: '16f1042a62f1bda20ebab8bfc1cb79c0be285c980dea6c2c733a17902631405b',
    body: '<path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0"/><circle cx="12" cy="10" r="3"/>',
  },
  'map-pinned': {
    category: 'contact',
    roles: ['contact-address'],
    sha256: '93239b2214c932ecab554ad4ac240664dd14993f850ff754dec29e6c25feec8f',
    body: '<path d="M18 8c0 3.613-3.869 7.429-5.393 8.795a1 1 0 0 1-1.214 0C9.87 15.429 6 11.613 6 8a6 6 0 0 1 12 0"/><circle cx="12" cy="8" r="2"/><path d="M8.714 14h-3.71a1 1 0 0 0-.948.683l-2.004 6A1 1 0 0 0 3 22h18a1 1 0 0 0 .948-1.316l-2-6a1 1 0 0 0-.949-.684h-3.712"/>',
  },
  'navigation': {
    category: 'contact',
    roles: ['contact-address'],
    sha256: '3c1adf655f06c733013ddf00848c3efe905ed70d7b3eba7a6be5e60e65880503',
    body: '<polygon points="3 11 22 2 13 21 11 13 3 11"/>',
  },
  /* ---- commerce (8) ---- */
  'shopping-bag': {
    category: 'commerce',
    roles: [],
    sha256: '24a161961b559234b7a31af904dab18b437507336ba2decff3fe6b7772495896',
    body: '<path d="M16 10a4 4 0 0 1-8 0"/><path d="M3.103 6.034h17.794"/><path d="M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z"/>',
  },
  'shopping-cart': {
    category: 'commerce',
    roles: [],
    sha256: '7cdc07053044af9e5fd24fff5e089ce97b2a39ea978933a160c4bbfebf8a167c',
    body: '<path d="m2.05 2.05 1.099-.028a1 1 0 0 1 1.008.815l2.69 14.347A1 1 0 0 0 7.83 18H18"/><path d="M4.563 5h16.435a1 1 0 0 1 .981 1.204l-1.026 6.226A2 2 0 0 1 18.962 14H6.25"/><circle cx="18" cy="20" r="2"/><circle cx="8" cy="20" r="2"/>',
  },
  'credit-card': {
    category: 'commerce',
    roles: [],
    sha256: '72d2b1acd904e01c6f676b4f6d07d56550a80b5d42687d43a313b85040943a2e',
    body: '<rect width="20" height="14" x="2" y="5" rx="2"/><line x1="2" x2="22" y1="10" y2="10"/><path d="M6 14h2"/>',
  },
  'tag': {
    category: 'commerce',
    roles: [],
    sha256: '85e11c07b29f5b67410e0f14c84799d9406320cd4575b7c8322f31910e0582cc',
    body: '<path d="M12.586 2.586A2 2 0 0 0 11.172 2H4a2 2 0 0 0-2 2v7.172a2 2 0 0 0 .586 1.414l8.704 8.704a2.426 2.426 0 0 0 3.42 0l6.58-6.58a2.426 2.426 0 0 0 0-3.42z"/><circle cx="7.5" cy="7.5" r=".5"/>',
  },
  'receipt-text': {
    category: 'commerce',
    roles: [],
    sha256: '35b44cd6ce443dc58119380750d6bc12b6dbead1cac23e7ac3dc578d52795bf4',
    body: '<path d="M13 16H8"/><path d="M14 8H8"/><path d="M16 12H8"/><path d="M4 3a1 1 0 0 1 1-1 1.3 1.3 0 0 1 .7.2l.933.6a1.3 1.3 0 0 0 1.4 0l.934-.6a1.3 1.3 0 0 1 1.4 0l.933.6a1.3 1.3 0 0 0 1.4 0l.933-.6a1.3 1.3 0 0 1 1.4 0l.934.6a1.3 1.3 0 0 0 1.4 0l.933-.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1 1.3 1.3 0 0 1-.7-.2l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.934.6a1.3 1.3 0 0 1-1.4 0l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-1.4 0l-.934-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-.7.2 1 1 0 0 1-1-1z"/>',
  },
  'package': {
    category: 'commerce',
    roles: [],
    sha256: '69d6bc7650d26c4d24dd55eb22791607b982ce7637073944c256f1f61575509d',
    body: '<path d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"/><path d="M12 22V12"/><polyline points="3.29 7 12 12 20.71 7"/><path d="m7.5 4.27 9 5.15"/>',
  },
  'truck': {
    category: 'commerce',
    roles: [],
    sha256: '1476faa56b56414ba5d5f01d15e851b8bfd79bef6c36f5855811c27590136e50',
    body: '<path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2"/><path d="M15 18H9"/><path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14"/><circle cx="17" cy="18" r="2"/><circle cx="7" cy="18" r="2"/>',
  },
  'banknote': {
    category: 'commerce',
    roles: [],
    sha256: '212d628014554424ec0041ab56e8869149d255b7077cfd6977d4ab2be32e8cb1',
    body: '<rect width="20" height="12" x="2" y="6" rx="2"/><circle cx="12" cy="12" r="2"/><path d="M6 12h.01M18 12h.01"/>',
  },
  /* ---- content (10) ---- */
  'file-text': {
    category: 'content',
    roles: [],
    sha256: '52ca55846c202335fb870c8aa23e9345630ec10489303756d62e750f7109605c',
    body: '<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"/><path d="M14 2v5a1 1 0 0 0 1 1h5"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>',
  },
  'book-open': {
    category: 'content',
    roles: [],
    sha256: '9b9bed0ff057283d5c5c5a1c71f8d3e927db26a56639603a92fdf7b25961510e',
    body: '<path d="M12 5v16"/><path d="M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z"/>',
  },
  'pen-line': {
    category: 'content',
    roles: [],
    sha256: '43c431457784ab409341b549119257111385e5af0a36dee08f37c91259c08799',
    body: '<path d="M13 21h8"/><path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/>',
  },
  'quote': {
    category: 'content',
    roles: [],
    sha256: '3c7a2f8443ae5c88cb3f35fdcc27a037a1af13fe35be28eb8cabded8672a9ac1',
    body: '<path d="M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z"/><path d="M5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z"/>',
  },
  'image': {
    category: 'content',
    roles: [],
    sha256: '619c9db58c879dce6250376ba67d9c9102ca6dbb3b1efb9294c9f180e22273a5',
    body: '<rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>',
  },
  'download': {
    category: 'content',
    roles: [],
    sha256: '3daeee13ded5a3afa2198b1bb4e2262d163922f97d96ac6ff9953e8ed4fe039d',
    body: '<path d="M12 15V3"/><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10 5 5 5-5"/>',
  },
  'newspaper': {
    category: 'content',
    roles: [],
    sha256: 'f5147e2a92a0ca16edea01782b09afeea7f9ebcda029d3f38ae93a3058ed1b78',
    body: '<path d="M15 18h-5"/><path d="M18 14h-8"/><path d="M4 22h16a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16a2 2 0 0 1-4 0v-9a2 2 0 0 1 2-2h2"/><rect width="8" height="4" x="10" y="6" rx="1"/>',
  },
  'message-square': {
    category: 'content',
    roles: [],
    sha256: '5812a3be783fdcd73efd2b6026e03131e4b8c6649e7d52aa2dc7bf2e2023a59d',
    body: '<path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"/>',
  },
  'messages-square': {
    category: 'content',
    roles: ['faq-answer'],
    sha256: '97733c58b74f8beddd569927f8453c86bca4afa394e6aad606db1acff4bd8355',
    body: '<path d="M16 10a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 14.286V4a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/><path d="M20 9a2 2 0 0 1 2 2v10.286a.71.71 0 0 1-1.212.502l-2.202-2.202A2 2 0 0 0 17.172 19H10a2 2 0 0 1-2-2v-1"/>',
  },
  'circle-question-mark': {
    category: 'content',
    roles: ['faq-answer'],
    sha256: '975db087da041530dbf59ba1e61a7b99c3519fad43dae6375e42ccc74ba63924',
    body: '<circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><path d="M12 17h.01"/>',
  },
  /* ---- data (8) ---- */
  'chart-line': {
    category: 'data',
    roles: [],
    sha256: '8736da84214736c4fd579b52b8a41f454cddf0dba9578618eee5ae8e22f40645',
    body: '<path d="M3 3v16a2 2 0 0 0 2 2h16"/><path d="m19 9-5 5-4-4-3 3"/>',
  },
  'chart-bar': {
    category: 'data',
    roles: [],
    sha256: '9035a34f1713a781e02af86b5b0d086c44ccb10f985c51a8fa2796211e88597b',
    body: '<path d="M3 3v16a2 2 0 0 0 2 2h16"/><path d="M7 16h8"/><path d="M7 11h12"/><path d="M7 6h3"/>',
  },
  'chart-pie': {
    category: 'data',
    roles: [],
    sha256: '1ae765b638fe588b392f7da6e2c274fb438b257d936f9f4c7d548c73d5f9d8a1',
    body: '<path d="M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z"/><path d="M21.21 15.89A10 10 0 1 1 8 2.83"/>',
  },
  'database': {
    category: 'data',
    roles: [],
    sha256: '471eb14bc8d144896a82dfc4aa9daf350f769f0896f4bef33e50aabdbb51130d',
    body: '<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/>',
  },
  'table': {
    category: 'data',
    roles: [],
    sha256: '806e2810a1dc693e5dcc22298c6bab50ca5ba16f090d5c61e8ca4b22fdeaa4e3',
    body: '<path d="M12 3v18"/><rect width="18" height="18" x="3" y="3" rx="2"/><path d="M3 9h18"/><path d="M3 15h18"/>',
  },
  'calculator': {
    category: 'data',
    roles: [],
    sha256: 'a6b191250b1ffabdf9fc9536662309f1b0f65336aa681d75bae9f1708baaefd0',
    body: '<rect width="16" height="20" x="4" y="2" rx="2"/><line x1="8" x2="16" y1="6" y2="6"/><line x1="16" x2="16" y1="14" y2="18"/><path d="M16 10h.01"/><path d="M12 10h.01"/><path d="M8 10h.01"/><path d="M12 14h.01"/><path d="M8 14h.01"/><path d="M12 18h.01"/><path d="M8 18h.01"/>',
  },
  'trending-up': {
    category: 'data',
    roles: [],
    sha256: 'c86a4afe20ceccd7a28e829a2cd83dbc40a8af51ffa9547332a9bac9a50a90ae',
    body: '<path d="M16 7h6v6"/><path d="m22 7-8.5 8.5-5-5L2 17"/>',
  },
  'activity': {
    category: 'data',
    roles: [],
    sha256: '050fbcda05e13c2051cf857683645e19c6b180861ef4d0cc28a6f09ba1ea1666',
    body: '<path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2"/>',
  },
  /* ---- process (8) ---- */
  'clock': {
    category: 'process',
    roles: ['schedule-time'],
    sha256: 'e9d3e3acf4d1c280fcf8092293439dc0a4756a908ceb859de144b12451cd1cb9',
    body: '<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',
  },
  'timer': {
    category: 'process',
    roles: ['schedule-time'],
    sha256: '6771297be65225d462c930865b6f9ee1617aa453885be4c8116a7512a77ac2b6',
    body: '<line x1="10" x2="14" y1="2" y2="2"/><line x1="12" x2="15" y1="14" y2="11"/><circle cx="12" cy="14" r="8"/>',
  },
  'calendar': {
    category: 'process',
    roles: ['schedule-date'],
    sha256: '312ac8e715ac2b71bcc942dec2e8de9c1929085474f08885af35b563f6aa7a0b',
    body: '<path d="M8 2v3"/><path d="M16 2v3"/><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18"/>',
  },
  'calendar-days': {
    category: 'process',
    roles: ['schedule-date'],
    sha256: '9330eb8d7c4989e97b6361314abbf02953243c602874725c9e58ceca00da3bd7',
    body: '<path d="M8 2v3"/><path d="M16 2v3"/><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18"/><path d="M8 13h.01"/><path d="M12 13h.01"/><path d="M16 13h.01"/><path d="M8 17h.01"/><path d="M12 17h.01"/><path d="M16 17h.01"/>',
  },
  'workflow': {
    category: 'process',
    roles: [],
    sha256: 'ae99ea8f56a2835a2cca35b2fbb57643ab73443610970dba23e24bd9df75cfec',
    body: '<rect width="8" height="8" x="3" y="3" rx="2"/><path d="M7 11v4a2 2 0 0 0 2 2h4"/><rect width="8" height="8" x="13" y="13" rx="2"/>',
  },
  'list-checks': {
    category: 'process',
    roles: [],
    sha256: '08d26ab05aaf724222c4c0cd5a19d5eae753b2a5fff0eb2d81759dde11bac6b6',
    body: '<path d="M13 5h8"/><path d="M13 12h8"/><path d="M13 19h8"/><path d="m3 17 2 2 4-4"/><path d="m3 7 2 2 4-4"/>',
  },
  'git-branch': {
    category: 'process',
    roles: [],
    sha256: '041f04acc8f92657b849540f0440e2e85d0df0b8da2365611e81b9bebfafc4eb',
    body: '<path d="M15 6a9 9 0 0 0-9 9V3"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/>',
  },
  'refresh-cw': {
    category: 'process',
    roles: [],
    sha256: '2e10dd403c85a24f163d59fc6151aa21147fe9402e1305dfc8979208caee8944',
    body: '<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/>',
  },
  /* ---- trust (9) ---- */
  'shield': {
    category: 'trust',
    roles: [],
    sha256: 'be32f6a86df7cbe43a83c439dd8849e5bcf5145e484d23420c20d8b98a78e82b',
    body: '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/>',
  },
  'shield-check': {
    category: 'trust',
    roles: [],
    sha256: '8d4fcdbde5bba4abb1a2f6fe53e37ceb6343a1d5449a9d88f6f97c1971d26c4e',
    body: '<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/><path d="m9 12 2 2 4-4"/>',
  },
  'lock': {
    category: 'trust',
    roles: [],
    sha256: 'd2cfe60cac8deaef36442b5c8218c1e61abe18222784b2a370ea090d13fca840',
    body: '<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',
  },
  'key': {
    category: 'trust',
    roles: [],
    sha256: '1f0bdf32374dacfca8cfc7f942c59d27a438e409dccaef11a8ce57de9365ae60',
    body: '<path d="m2 21 9.6-9.6"/><path d="m7.5 15.5 2.3 2.3a1 1 0 0 1 0 1.4l-2.1 2.1a1 1 0 0 1-1.4 0L4 19"/><circle cx="15.5" cy="7.5" r="5.5"/>',
  },
  'badge-check': {
    category: 'trust',
    roles: ['pricing-included'],
    sha256: 'a83b36e35ed35be896c5e5d39d0a63ba4368735ac22f09a26a31726259467775',
    body: '<path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z"/><path d="m16 9-5.5 5.5L8 12"/>',
  },
  'circle-check': {
    category: 'trust',
    roles: ['pricing-included'],
    sha256: '9711e045a5999f8a3b0782eb88e09b04e0559bc7b379dcc0a4ae645223e10345',
    body: '<circle cx="12" cy="12" r="10"/><path d="m16 9-5.5 5.5L8 12"/>',
  },
  'check': {
    category: 'trust',
    roles: ['pricing-included'],
    sha256: '7f33acc9a77a61659531044525fc008edebe215bf4dcf1c789c8674ad3277db0',
    body: '<path d="M20 6 9 17l-5-5"/>',
  },
  'award': {
    category: 'trust',
    roles: [],
    sha256: '4d9818ae68bb0776cbec9e65d26a33c7854eff600f33fcd6268e67b9d1caa06d',
    body: '<path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526"/><circle cx="12" cy="8" r="6"/>',
  },
  'users': {
    category: 'trust',
    roles: [],
    sha256: 'eeed488a1ec95ba730dd69996536fb65061d6ea273afb2429ae47e65eebf401c',
    body: '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><path d="M16 3.128a4 4 0 0 1 0 7.744"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/>',
  },
  /* ---- decoration (8) ---- */
  'sparkles': {
    category: 'decoration',
    roles: [],
    sha256: 'f5499f33f09d7158151e9bd2ec0faf79ff8fb57292f84fdd7286d96d0f0424d8',
    body: '<path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z"/><path d="M20 2v4"/><path d="M22 4h-4"/><circle cx="4" cy="20" r="2"/>',
  },
  'star': {
    category: 'decoration',
    roles: [],
    sha256: 'c59da86b889569387db28e69ad00a89f96af22863ad9eea9aa12c4876a14338c',
    body: '<path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"/>',
  },
  'heart': {
    category: 'decoration',
    roles: [],
    sha256: '70af5f30be9fcb500b852556b38dcdf8c04a4ba81fd262534fb0336bd39b3b52',
    body: '<path d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"/>',
  },
  'sun': {
    category: 'decoration',
    roles: [],
    sha256: 'a3955c8b0425fcc5c9ba12d2bdd77fe53b2cd5dd05e7742a56f342e996fb2ef8',
    body: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>',
  },
  'moon': {
    category: 'decoration',
    roles: [],
    sha256: '205b959e940d5841f0ce1d09c933153da9d9c94130a54d5cc0c68c2af1d403da',
    body: '<path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"/>',
  },
  'leaf': {
    category: 'decoration',
    roles: [],
    sha256: 'ac2b65d8d35b5038c9388cd1f161e74570fce6ef6a4c3d99a6b0c2bd68e0cb28',
    body: '<path d="M11 20a10 10 0 0010-10 25.9 25.9 0 00-1.04-7.281 1 1 0 00-1.755-.325C15.833 5.5 13 5.5 9.8 6.1A7 7 0 0011 20"/><path d="M2 21a5 5 0 012.911-4.544C7.613 15.212 8.351 15.24 11 13"/>',
  },
  'zap': {
    category: 'decoration',
    roles: [],
    sha256: '4c395891eab4d1e5627c5d414a16db037317cb2f12453de0f3a1130964c6d444',
    body: '<path d="M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z"/>',
  },
  'flower': {
    category: 'decoration',
    roles: [],
    sha256: '52d9db5e1448d213e81954d8fbd331ca2bb8849a4be5adf9426e5683e7ee8b85',
    body: '<circle cx="12" cy="12" r="3"/><path d="M12 16.5A4.5 4.5 0 1 1 7.5 12 4.5 4.5 0 1 1 12 7.5a4.5 4.5 0 1 1 4.5 4.5 4.5 4.5 0 1 1-4.5 4.5"/><path d="M12 7.5V9"/><path d="M7.5 12H9"/><path d="M16.5 12H15"/><path d="M12 16.5V15"/><path d="m8 8 1.88 1.88"/><path d="M14.12 9.88 16 8"/><path d="m8 16 1.88-1.88"/><path d="M14.12 14.12 16 16"/>',
  },
};
